pre-commit:
  parallel: true
  commands:
    rubocop:
      tags: backend
      glob: "**/*.{rb,rake}"
      run: bundle exec rubocop --force-exclusion
    packwerk-validate:
      tags: packwerk
      run: bundle exec packwerk validate
    packwerk-check:
      tags: packwerk
      glob: "**/*.rb"
      run: bundle exec packwerk check
    rspec:
      tags: test
      run: RAILS_ENV=test bin/rails db:test:prepare && bundle exec rspec --fail-fast

pre-push:
  commands:
    brakeman:
      tags: security
      run: bundle exec brakeman -q --no-progress --no-pager
    bundler-audit:
      tags: security
      run: bundle exec bundler-audit check
    rspec:
      tags: test
      run: RAILS_ENV=test bin/rails db:test:prepare && bundle exec rspec
