inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-packs

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  TargetRailsVersion: 7.2
  Exclude:
    - 'tmp/cache/packwerk/**/*'

# frozen_string_literal マジックコメントを強制
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  SafeAutoCorrect: true

# RSwagのDSLはRuboCopから空のexample groupとして見えるため無効化
RSpec/EmptyExampleGroup:
  Enabled: false

# テストの可読性を優先し、長さや期待値の数を制限しない
RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

# テストコンテキストの命名規則を緩和
RSpec/ContextWording:
  Enabled: false

# letの命名規則を緩和（money1, money2など意味が明確な場合は許可）
RSpec/IndexedLet:
  Enabled: false

# 同一値の比較も明示的なテストとして許可
RSpec/IdenticalEqualityAssertion:
  Enabled: false

# モジュラーモノリス境界を強制するPackwerk cops
# NOTE: 以下のパターンはクラスメソッドを公開APIとして許可する例外
# - ActiveRecordモデル: app/packages/*/app/public/*.rb (直下のモデルファイル)
# - Concern: app/packages/*/app/public/**/*(concern|able).rb (Concernパターン)
Packs/ClassMethodsAsPublicApis:
  Enabled: true
  Exclude:
    - 'app/packages/*/app/public/*.rb'  # ActiveRecordモデル（public直下）
    - 'app/packages/*/app/public/**/*able.rb'  # Concern命名規則（*ableで終わる）

Packs/DocumentedPublicApis:
  Enabled: false  # ドキュメントの成熟度が上がったら有効化可能

Packs/RootNamespaceIsPackName:
  Enabled: true

# NOTE: omakaseの間接依存でSorbetがinstallされているが利用していないのでSorbetのcopsは無効にしている
Sorbet/FalseSigil:
  Enabled: false

Sorbet/HasSigil:
  Enabled: false

Sorbet/IgnoreSigil:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: false

Sorbet/StrongSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: false

Sorbet/EnforceSingleSigil:
  Enabled: false

Sorbet/ForbidRBIOutsideOfAllowedPaths:
  Enabled: false

Sorbet/SignatureBuildOrder:
  Enabled: false

Sorbet/SingleLineRbiClassModuleDefinitions:
  Enabled: false

Sorbet/ForbidSig:
  Enabled: false

Sorbet/ForbidTUntyped:
  Enabled: false

Sorbet/EnforceSignatures:
  Enabled: false

Sorbet/ForbidSuperclassConstLiteral:
  Enabled: false

Sorbet/ForbidTBind:
  Enabled: false

Sorbet/CallbackConditionalsBinding:
  Enabled: false