inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rails
  - rubocop-performance
  # - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  TargetRailsVersion: 7.2